#include "Yellow.h"
#include "Runtime.h"
#include "Errors.h"

STUB_UNIMPLEMENTED(ADD);
STUB_UNIMPLEMENTED(SUB);
STUB_UNIMPLEMENTED(MUL);
STUB_UNIMPLEMENTED(DIV);
STUB_UNIMPLEMENTED(MOD);
STUB_UNIMPLEMENTED(REM);
STUB_UNIMPLEMENTED(ROUND);
STUB_UNIMPLEMENTED(TRUNCATE);
STUB_UNIMPLEMENTED(FLOOR);
STUB_UNIMPLEMENTED(CEILING);
STUB_UNIMPLEMENTED(MIN);
STUB_UNIMPLEMENTED(MAX);
STUB_UNIMPLEMENTED(EXP);
STUB_UNIMPLEMENTED(EXPT);
STUB_UNIMPLEMENTED(LOG);
STUB_UNIMPLEMENTED(SQRT);
STUB_UNIMPLEMENTED(ABS);
STUB_UNIMPLEMENTED(SIN);
STUB_UNIMPLEMENTED(COS);
STUB_UNIMPLEMENTED(TAN);
STUB_UNIMPLEMENTED(ASIN);
STUB_UNIMPLEMENTED(ACOS);
STUB_UNIMPLEMENTED(ATAN);
STUB_UNIMPLEMENTED(RANDOM);
